name: "Kics scan"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 0 * * *"

jobs:
  Analyze charts:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - uses: actions/checkout@v3

      - name: Kics scan
        uses: checkmarx/kics-github-action@v1.6
        with:
          path: "."
          fail_on: high
          disable_secrets: false
          output_path: kicsResults/
          output_formats: "json,sarif"

      - name: Upload SARIF file for GitHub Advanced Security Dashboard
        if: always()
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: kicsResults/results.sarif
