image:
  tag: $ARGOCD_APP_REVISION

springprofile: dev

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
  hosts:
    - host: "boilerplate.dev.some.project.com"
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - hosts:
      - "boilerplate.dev.some.project.com"
      secretName: tls-secret

datasource:
  url: jdbc:postgresql://localhost:5432/boilerplate
  username: boilerplate
  password: <path:traceability-foss/data/dev/database#tracePassword>


postgresql:
  enabled: true
  auth:
    database: "TODO"
    password: "TODO"
    postgresPassword: "TODO"

pgadmin4:
  enabled: true
  strategy:
    type: Recreate
  networkPolicy:
    enabled: false
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/backend-protocol: HTTP
    hosts:
      - host: boilerplate.dev.some.project.com
        paths:
          - path: /
            pathType: Prefix
    tls:
      - hosts:
          - boilerplate.dev.some.project.com
        secretName: tls-secret
  env:
    email: "TODO"
    password: "TODO"
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi
