{{- if .Values.imagePullSecret.dockerconfigjson }}
---
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  name: {{ include "kotlin-spring-hexagonal.fullname" . }}-imagepullsecret
  labels:
    {{- include "kotlin-spring-hexagonal.labels" . | nindent 4 }}
data:
  .dockerconfigjson: {{ .Values.imagePullSecret.dockerconfigjson }}
type: kubernetes.io/dockerconfigjson
  {{- end }}