{{- if .Values.serviceAccount.create -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  name: {{ include "kotlin-spring-hexagonal.serviceAccountName" . }}
  labels:
    {{- include "kotlin-spring-hexagonal.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
